spring.application.name=Online-Food-Ordering
spring.datasource.url = ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/food}
spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
spring.datasource.username = ${DBMS_USERNAME:root}
spring.datasource.password = ${DBMS_PASSWORD:Hung23072004}
server.servlet.context-path= /food
server.port=8080
spring.jpa.hibernate.ddl-auto = update
jwt.signerKey=S5eUx6DQSJ3ce3Dokj+qZmVlpj3hG7M841wX3NEj3oMcPwx6+oOA9AdHzbZE3Nb8
jwt.valid-duration= 36000 
jwt.refreshable-duration =36000
logging.level.org.springframework.security=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hungabc2307@gmail.com
spring.mail.password=kblwzwaamhqyokjc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.expiryTime=3600


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# ================== Google OAuth2 ==================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/food/auth/oauth2/callback/google


# ================== Facebook OAuth2 ==================
spring.security.oauth2.client.registration.facebook.client-id=2136050530221270
spring.security.oauth2.client.registration.facebook.client-secret=5b054f438d58b354bd76ab627925092b
spring.security.oauth2.client.registration.facebook.scope=public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/food/auth/oauth2/callback/facebook

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
logging.level.org.springframework.cache=DEBUG

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=mybucket

# ================== Elasticsearch Configuration ==================
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=admin123
spring.data.elasticsearch.repositories.enabled=true
spring.elasticsearch.connection-timeout=5s
spring.elasticsearch.socket-timeout=60s